### ISSUE TITLE
Process crash when selecting a value in ManyToMany field

### ISSUE THREAD

**Issue by neerfri** [naymspace/backpex#451]
Hi,

First thank you for this amazing library 🙏 🙏 🙏 

I'm having an issue creating a `ManyToMany` field.
Whenever I try to select a value (in this case a `Label` for a `Sample`) the process crashes.

Here is the trace:
```
[error] GenServer #PID<0.4326.0> terminating
** (BadMapError) expected a map, got: nil
    (elixir 1.17.1) lib/map.ex:535: Map.get(nil, :name, nil)
    (backpex 0.5.1) lib/backpex/fields/many_to_many.ex:386: Backpex.Fields.ManyToMany.to_form_option/2
    (elixir 1.17.1) lib/enum.ex:1703: Enum."-map/2-lists^map/1-1-"/2
    (backpex 0.5.1) lib/backpex/fields/many_to_many.ex:210: Backpex.Fields.ManyToMany.render_form/1
    (phoenix_live_view 1.0.0-rc.6) lib/phoenix_live_view/renderer.ex:79: Phoenix.LiveView.Renderer.to_rendered/2
    (phoenix_live_view 1.0.0-rc.6) lib/phoenix_live_view/diff.ex:335: Phoenix.LiveView.Diff.component_to_rendered/3
    (phoenix_live_view 1.0.0-rc.6) lib/phoenix_live_view/diff.ex:753: Phoenix.LiveView.Diff.render_component/8
    (phoenix_live_view 1.0.0-rc.6) lib/phoenix_live_view/diff.ex:214: Phoenix.LiveView.Diff.write_component/4
    (phoenix_live_view 1.0.0-rc.6) lib/phoenix_live_view/channel.ex:662: Phoenix.LiveView.Channel.component_handle/4
    (stdlib 6.0) gen_server.erl:2173: :gen_server.try_handle_info/3
    (stdlib 6.0) gen_server.erl:2261: :gen_server.handle_msg/6
    (stdlib 6.0) proc_lib.erl:329: :proc_lib.init_p_do_apply/3
```

I'd appreciate your help in finding what am I doing wrong.

❤️

**Comment by io2** [comment]
Hi @neerfri 

From the error, (and this is guessing only), you might have some null data in your database causing this error. However, it would be pretty impossible to really help without some additional information on your end?

Share your LiveResource & Schema (model) code. Or at a minimum - the code snippet showing how you can configuring the fields.

**Comment by thomasfortes** [comment]
Probably it is the same issue that I'm having right now, and it is because backpex doesn't work that well with serial values and I tracked the issue to the Enum.find at: https://github.com/naymspace/backpex/blob/50b47c9c1e35a5bc524836db3283a0acc3c9adf6/lib/backpex/fields/has_many.ex#L247-L257

The id field is passed as an string, but it is an integer in the struct, so we don't find anything ever, the ideal solution would be support for serial numbers, but for now I fixed it copying the field to my project and replacing both the `Enum.find` for `Enum.find(selected, fn option -> option.id == String.to_integer(id))`.

If the project is new I recommend using bigserial or uuids for your ids, if don't this is a temporary fix.

**Comment by Flo0807** [comment]
> [...] I fixed it copying the field to my project and replacing both the Enum.finds for Enum.find(selected, fn option -> option.id == String.to_integer(id) end) and the Enum.reject for Enum.reject(selected, fn option -> option.id == String.to_integer(id) end)

If I understand correctly, this will fix the problem? Do you want to provide a PR for it?
